version: '3.9'

services:
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password